### ISSUE TITLE
feedback during create-proton-app

### ISSUE THREAD

**Issue by vikkio88** [albe-rosado/create-proton-app#10]
Hey there,
This framework sounds like an amazing idea, I am trying it now, and I saw your point on the readme about suggesting any improvement.
I have a few
1. Improve visual feedback, it is ok to say "it might take a while", but it would be better if you reported at each step what is happening, so the user will not just wait on a black screen thinking that everything froze.
2. I dont understand why you are adding via npm on install rather than having the whole package.json with the right dependencies already there and just running yarn or npm install
3. Would be nice if you used [chalk](https://github.com/chalk/chalk) or any other node cli util to show better output on the console

Thanks for this anyway, if anything else comes up to my mind I will be happy to report back.

**Comment by albe-rosado** [comment]
Nice! and thanks a lot. Right now as of version 1.1.5, the cli logs everything, and I don't use chalk because I'm personally not a big fan of using 3rd party libraries that don't provide any substantial value. that's why I use ascii colors, easy to use and avoid having huge deps. At the end, this is just a simple cli app to help get you started. But I agree with you, we could show something like:
```
[x] copying template
[x] installing deps
[ ] doing something else...
```
with the nice spin and stuff,
looks better and is more informative.
About your second concern. would be faster to just copy the `package.json` file and let the user do `npm install`, I felt more natural if the user could start the app right after the install finish, like react, electron-forge or angular does.

**Comment by mischnic** [comment]
> About your second concern. would be faster to just copy the package.json file and let the user do npm install, I felt more natural if the user could start the app right after the install finish, like react, electron-forge or angular does.

create-proton-app can run `npm install` after copying the package file. The difference is that running it once is faster.

**Comment by vikkio88** [comment]
> About your second concern. would be faster to just copy the package.json file and let the user do npm install, I felt more natural if the user could start the app right after the install finish, like react, electron-forge or angular does.

I am not telling you to avoid running `npm install` on `create-proton-app`, I am telling you to avoid doing this
```js
 const dependencies = ['electron-builder', 'babel-cli', 'babel-preset-env', 'babel-preset-stage-0', 'babel-preset-react'];
    // Install dependecies
    const command = `npm${runningOnWindows ? '.cmd' : ''}`; // Supporting only npm initially, yarn will come in the future(maybe)
    const args = ['install', '--save-dev', '--loglevel', 'error', ...dependencies];
    if (verbose) {
        args.push('--verbose');
    }
```

which is basically
```
npm install electron-builder babel-cli ....
```
but doing just
```
npm install
```

and leave those dependencies on the `package.json` file template.

**Comment by albe-rosado** [comment]
That piece of logic was meant to install proton-native only, something happened that I or kusti had to add those others. I see your point and you are right @vikkio88 . will change that this weekend , thank you :-)

**Comment by vikkio88** [comment]
@albe-rosado  I noticed as well that react is not a direct dependency, it would be nice to add it as a dev dependency at least

**Comment by mischnic** [comment]
It is a direct dependency

https://github.com/albe-rosado/create-proton-app/blob/c4ad5c62054a27ccd0c532d076e28e680425df62/template/index.js#L1

JSX doesn't work without that `React` import and you can't create new component classes without `Component`.

**Comment by vikkio88** [comment]
it is indeed, @mischnic, but it is not listed as such on the `packages.json` generated:
```json
{
  "name": "example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js",
    "build": "node_modules/.bin/babel index.js -d bin/",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  "build": {
    "protonNodeVersion": "current",
    "mac": {
      "identity": null
    }
  },
  "dependencies": {
    "proton-native": "^1.1.1"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "electron-builder": "^20.11.1"
  }
}
```

It does work as it is an internal dependency of `proton-native`, but using it in here, as you shown it should be listed in the `packages.json`

**Comment by albe-rosado** [comment]
Help me to understand, what would be the benefit of having `react` as a duplicated dependency? @mischnic

**Comment by mischnic** [comment]
> Help me to understand, what would be the benefit of having react as a duplicated dependency?

kusti8 in https://github.com/kusti8/proton-native/issues/119#issuecomment-388499007:

> I agree that a peer dependency would be ideal, but create-proton-app would have to be updated as well to install react, as well as existing projects. If this becomes a large issue I'll change it, but for now I'll let it be a dependency.
