### ISSUE TITLE
Blurry window after build

### ISSUE THREAD

**Issue by eveningkid** [albe-rosado/create-proton-app#13]
The window looks just fine when using `npm run start`. 
The issue appears after I run the generated application from `npm run dist`.

I guess the following screenshot is pretty explicit:
<img width="619" alt="screenshot at may 17 19-42-09" src="https://user-images.githubusercontent.com/7188494/40175412-9ba2d660-5a0a-11e8-8c29-982fe3bda356.png">
_Built on macOS high sierra (10.13.4)_

I have no idea if this could be in any way related to electron builder configuration.
If you need any specific detail, please let me know.

Thank you for all your work, this project is really cool. 
Hope it can become big! :)

**Comment by mischnic** [comment]
If you edit the Info.plist file in `MyApp.app/Contents` and add 
```
	<key>NSHighResolutionCapable</key>
	<true/>
```
just before the last 
```
</dict>
</plist>
```
is it still blurry?


@develar Is this handled by electron-builder?

**Comment by eveningkid** [comment]
@mischnic with `NSHighResolutionCapable`, it works fine. 
It would be great to automatically add it to the plist file.

**Comment by albe-rosado** [comment]
That has to be done on the electron-builder side I believe, @mischnic   are we opening an issue with them? @eveningkid  thanks for the catch.

**Comment by mischnic** [comment]
Opened an issue. This can be closed.

**Comment by albe-rosado** [comment]
@mischnic thanks a lot

**Comment by mischnic** [comment]
As a workaround, there is a configuration option for additional entries:
This *might* work:
```json
{
	"mac": {
		"extendInfo": {"NSHighResolutionCapable": true}
    }
} 
```

**Comment by albe-rosado** [comment]
will try that and add it, anyway, when it gets fixed on their side, there won't be any problem with having that set, I think.

**Comment by mischnic** [comment]
I doubt it works, because it's only getting handled in the electron specific code... 😞

**Comment by develar** [comment]
Please try electron-builder 20.14.2 (it is tagged as `next`, will be marked as `latest` tomorrow, because of new build service that used by 20.14.0+).
