### ISSUE TITLE
info lifecycle libui-node@0.2.1~build: Failed to exec build script

### ISSUE THREAD

**Issue by tenfromfive** [albe-rosado/create-proton-app#22]
Hey all,

I am trying to install/run proton native via create-proton-app on Ubuntu 18.04.  When I install using the quickstart directions [(quickstart)](https://proton-native.js.org/#/quickstart) npm gives me "`An error ocurred: npm install has failed" and exits without finishing.`  Interestingly, it still creates index.js, node_modules, and package.json, but if I try to run "`npm run start`," I obtain "`Error: Cannot find module 'proton-native'`."  Tracing through the npm logs, it looks like create-proton-app is failing at "`info lifecycle libui-node@0.2.1~build: Failed to exec build script.`"  Some of the fixes that I have already tried:

1. Checked for directories with spaces in the project's path.  Didn't find any.
2. Deleted node_modules and ran npm install.  Same error appears.
3. Elevated to root, reinstalled from scratch, same error appears.
4. Made sure that I have the appropriate dependencies as defined in the directions.

Interestingly, if I follow the manual install procedure [here](https://proton-native.js.org/#/manual_install), & then do `npm run start`, it works just fine (although `npm run dist fails` identically to [this issue](https://github.com/electron-userland/electron-builder/issues/3549) for electron-builder (probably unrelated, but who knows...).

Short error log for `create-proton-app test` is pasted here:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle libui-node@0.2.1~prebuild: libui-node@0.2.1
6 info lifecycle libui-node@0.2.1~build: libui-node@0.2.1
7 verbose lifecycle libui-node@0.2.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle libui-node@0.2.1~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/eric/projects/test/node_modules/libui-node/node_modules/.bin:/home/eric/projects/test/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/eric/projects/test/node_modules/libui-node/node_modules/.bin:/home/eric/projects/test/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/snap/bin
9 verbose lifecycle libui-node@0.2.1~build: CWD: /home/eric/projects/test/node_modules/libui-node
10 silly lifecycle libui-node@0.2.1~build: Args: [ '-c', 'node-gyp configure build' ]
11 silly lifecycle libui-node@0.2.1~build: Returned: code: 1  signal: null
12 info lifecycle libui-node@0.2.1~build: Failed to exec build script
13 verbose stack Error: libui-node@0.2.1 build: `node-gyp configure build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid libui-node@0.2.1
15 verbose cwd /home/eric/projects/test/node_modules/libui-node
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error libui-node@0.2.1 build: `node-gyp configure build`
22 error Exit status 1
23 error Failed at the libui-node@0.2.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tenfromfive** [comment]
Long error log is attached.
[long.log](https://github.com/albe-rosado/create-proton-app/files/2739883/long.log)

**Comment by mischnic** [comment]
Do you have `build-essential` and GTK+3 installed?

**Comment by tenfromfive** [comment]
libgtk-3-dev & build-essential both installed through  apt

**Comment by tenfromfive** [comment]
@mischnic, good call.  switched with `nvm use 8`, which worked for `create-proton-app`, `npm run start`, and `npm-run-build`.  Now on to the second error from my original post...`nvm run dist` is failing at `electron-biulder` in a fashion identical to [this issue](https://github.com/electron-userland/electron-builder/issues/3549) (see below for `npm run dist` output/attachment for log).

In the issue that I referenced, it seems like there was a fix that has already been implemented for `electron-builder`, is it possible to bring that fix into the proton native project?

===============================================================================
`eric@eric-T480s-ubuntu:~/projects/testing$ npm run dist

> testing@0.0.1 dist /home/eric/projects/testing
> electron-builder

  • electron-builder version=20.38.4
  • loaded configuration file=package.json ("build" field)
  • description is missed in the package.json appPackageFile=/home/eric/projects/testing/package.json
  • author is missed in the package.json appPackageFile=/home/eric/projects/testing/package.json
  • writing effective config file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 proton=8.15.0 appOutDir=dist/linux-unpacked
  • transpile source code using Babel options=
                                        {
                                          "ast": false,
                                          "sourceMaps": "inline"
                                        }
  • building        target=snap arch=x64 file=dist/testing_0.0.1_amd64.snap
  • building        target=AppImage arch=x64 file=dist/testing 0.0.1.AppImage
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  • application Linux category is set to default "Utility" reason=linux.category is not set and cannot map from macOS docs=https://electron.build/configuration/configuration#LinuxBuildOptions-category
  ⨯ at least snapcraft 2.40.0 is required, please: sudo snap install snapcraft --classic
Error: /home/eric/projects/testing/node_modules/app-builder-bin/linux/x64/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (/home/eric/projects/testing/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at SnapTarget.build (/home/eric/projects/testing/node_modules/app-builder-lib/src/targets/snap.ts:148:44)
    at Function.buildAsyncTargets (/home/eric/projects/testing/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at LinuxPackager.packageInDistributableFormat (/home/eric/projects/testing/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at /home/eric/projects/testing/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at LinuxPackager.pack (/home/eric/projects/testing/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at /home/eric/projects/testing/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/eric/projects/testing/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/eric/projects/testing/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/eric/projects/testing/node_modules/app-builder-lib/src/packager.ts:396:24)
    at /home/eric/projects/testing/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at /home/eric/projects/testing/node_modules/graceful-fs/graceful-fs.js:111:16
    at /home/eric/projects/testing/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/eric/projects/testing/node_modules/app-builder-lib/src/packager.ts:335:133)
    at /home/eric/projects/testing/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (/home/eric/projects/testing/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (/home/eric/projects/testing/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/home/eric/projects/testing/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/home/eric/projects/testing/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing@0.0.1 dist: `electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing@0.0.1 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eric/.npm/_logs/2019-01-09T22_04_03_809Z-debug.log`
[log2.log](https://github.com/albe-rosado/create-proton-app/files/2742851/log2.log)

**Comment by mischnic** [comment]
> in a fashion identical to this issue (see below for npm run dist output/attachment for log).
>
> In the issue that I referenced, it seems like there was a fix that has already been implemented for electron-builder, is it possible to bring that fix into the proton native project?

If you take a look at the log you posted, you can see that we are actually using electron-builder (which supports packaging proton-native apps by itself):
```
electron-builder

  • electron-builder version=20.38.4
```

The issue you linked contains responses recent that the issue isn#t actually fixed in 20.38.4.

**Comment by tenfromfive** [comment]
@mischnic ok thanks.  For my clarity, when the issue is fixed by `electron-builder`, will `create-proton-app` automatically pull the release with the fix?

**Comment by tenfromfive** [comment]
Perfect.  Closing the issue, thanks for all the help.
