### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by kusti8** [albe-rosado/create-proton-app#4]
Hi,

I found a bug in the packaging section. `package.json` should be:

```
  "scripts": {
    "start": "node_modules/.bin/babel-node index.js",
    "build": "node_modules/.bin/babel index.js -d bin/",
  }
```

Notice the removal of index.js after bin. Sorry about that.

**Comment by albe-rosado** [comment]
ha! I just noticed like an hour ago, otherwise, you will get the bundled files on `bin/index.js/` instead of `bin/`. yeah, I;m going to fix that.

**Comment by albe-rosado** [comment]
just fixed it, thanks @kusti8
